openchat/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path(
        '',
        views.login,
        name="login"
        ),
    path(
        'conversations',
        views.conversation_list,
        name='conversation_list'
        ),
    path(
        'conversations/create-conversation',
        views.create_conversation,
        name='create_conversation'
    ),
    path(
        'conversations/<conversation>',
        views.message_list,
        name='message_list'
        ),
    path(
        'signup',
        views.signup,
        name='sign_up'
    ),
    path('logout', views.logout, name='logout'),
]

openchat/openchat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

openchat/chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Conversation(models.Model):
    name = models.CharField(max_length=30, unique=True, default="Void")
    users = models.ManyToManyField(User)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        to_field="username",
        related_name="author",
        )

    def __str__(self):
        return self.name


class Message(models.Model):
    text = models.CharField(max_length=999)
    date = models.DateTimeField(auto_now=True)
    conversation = models.ForeignKey(
        Conversation,
        on_delete=models.CASCADE,
        to_field="name"
        )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        to_field="username",
        )

    def __str__(self):
        if len(self.text) <= 20:
            return "{} // sent {}:{}, by {}".format(
                self.text,
                self.date.hour,
                self.date.minute,
                self.author,
                )

        return "{}... // sent {}:{}, by {}".format(
            self.text[:20],
            self.date.hour,
            self.date.minute,
            self.author,
            )

openchat/chat/forms.py
from django import forms
from .models import Conversation, Message


class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['name', 'users']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']

openchat/chat/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login as do_login, logout as do_logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required


from .models import Message, Conversation
from .forms import ConversationForm, MessageForm


@login_required
def conversation_list(request):
    conversations = Conversation.objects.filter(
        users=request.user
        )

    messages = {}
    for conversation in conversations:
        messages[conversation.name] = Message.objects.filter(
            conversation=conversation).order_by('-date')[:5]

    return render(
        request,
        'chat/conversation_list.html',
        {'conversations': conversations, 'messages': messages},
        )

@login_required
def message_list(request, conversation):
    messages = reversed(Message.objects.filter(conversation=conversation))
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = Message.objects.create(
                text=form.cleaned_data['text'],
                conversation=Conversation.objects.get(name=conversation),
                author=request.user,
            )
            new_message.save()

        form = MessageForm()
        return HttpResponseRedirect("")

    else:
        form = MessageForm()

    return render(
        request,
        'chat/message_list.html',
        {
            'messages': messages,
            'user': request.user,
            'form': form,
            },
        )


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('conversations')

    else:
        if request.method == 'POST':
            form = AuthenticationForm(data=request.POST)

            form.is_valid()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                do_login(request, user)
                return HttpResponseRedirect('conversations')

        else:
            form = AuthenticationForm()

        return render(request, 'chat/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            do_login(request, user)
            return HttpResponseRedirect('conversations')

    else:
        form = UserCreationForm()
    return render(request, 'chat/signup.html', {'form': form})

@login_required
def create_conversation(request):
    if request.method == 'POST':
        form = ConversationForm(request.POST)
        if form.is_valid():
            new_conversation = Conversation.objects.create(
                name=form.cleaned_data['name'],
                author=request.user,
                )
            new_conversation.users.set(form.cleaned_data['users'])
            new_conversation.save()
            return HttpResponseRedirect(
                '{}'.format(new_conversation.name)
                )

    else:
        form = ConversationForm(request.POST)
    return render(request, 'chat/create_conversation.html', {'form': form})


def logout(request):
    do_logout(request)
    return HttpResponseRedirect("/chat/")

openchat/chat/templates/chat/conversation_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'chat/conversation_list.css' %}">
    <title>Conversations</title>
</head>
<body>
    <div class="list_of_conversations">
        {% if conversations %}
            <ul id="conversation_list">
                {% for conversation in conversations %}
                    <li id="conversation">
                        <a href="{% url 'chat:message_list' conversation %}" id="conversation_link">{{ conversation.name }}</a>
                        <ul id="message_list">
                            {% load filters %}
                            {% for message in messages|messages_by_conversation:conversation %}
                                <li id="message">{{message}}</li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
    </div>
    {% else %}
        <p>You haven't started any conversations yet!</p>
    {% endif%}
    <button class="button"><a href="conversations/create-conversation">Create Conversation</a></button>
    <button class="button"><a href="/chat/logout">Logout</a></button>

</body>
</html>

openchat/chat/templates/chat/create_conversation.html
<!DOCTYPE html>
<html>
<head>
    <title>Openchat</title>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/create_conversation.css' %}">
</head>
<body>
    <h2>Create conversation</h2>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small>{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <input type="submit" class="button" value="Create">
    </form>
    
</body>
</html>

openchat/chat/templates/chat/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Openchat</title>

    <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Capriola' rel='stylesheet'>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/login.css' %}">
</head>
<body>
    <h1 class="Title">Openchat</h1>
    <form method="POST">
        {% csrf_token %}

        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small>{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}<br><br>
        
       
        <input type="submit" class="button" id="submit" value="Login">
        <button type="button" class="button"><a href="signup">Sign up</a></button>
    </form>
        
    
</body>
</html>

openchat/chat/templates/chat/message_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'chat/message_list.css' %}">

    <title>Conversation</title>

</head>
<body>   
        {% if messages %}
            <ul class="message_list">
                {% for message in messages %}
                {% if message.author == user %}
            <div class="message-mine">
                <li>
                    <p class="message_text">{{message.text}}</p><p class="message_info">{{message.date}}, by {{message.author}}</p>                 
                </li>
            </div>

                    
                {% else %}
                <div class="message-other">
                <li>
                   <p class="message_text">{{message.text}}</p><p class="message_info">{{message.date}}, by {{message.author}}</p>
                </li>
               </div>
                {% endif %}
                {% endfor %}
            </ul>

    {% else %}
        <p class="no_messages">You haven't sent any messages yet!</p>
    {% endif%}

    <form method="POST">
        <div class = "new_message">
        {% csrf_token %}
        {% for field in form %}
            {{ field }}
        {% endfor %}
        <input type="submit" class="button" id="send_button" value="Send">
        </div>
    </form>

    <button class="button" id="back_button"><a href="../">back</a></button>


</body>
</html>

openchat/chat/templates/chat/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Openchat</title>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/signup.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Capriola' rel='stylesheet'>
</head>
<body>
    <div class="Title"><h1>Sign up</h1></div>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <br><small>{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <input type="submit" class="button" value="Sign up">
    </form>
    
</body>
</html>